
CREATE TABLE JOB
(
  TypeCode INT NOT NULL,
  Description VARCHAR(15) NOT NULL,
  PRIMARY KEY (TypeCode)
);


CREATE TABLE EMPLOYEES
(
  EmpNumber INT NOT NULL,
  SSN CHAR(16) NOT NULL,
  Fname VARCHAR(15) NOT NULL,
  LName VARCHAR(20) NOT NULL,
  DOB DATE NOT NULL,
  Gender CHAR(1) NOT NULL,
  PhoneNum VARCHAR(14) NOT NULL,
  Street VARCHAR(30) NOT NULL,
  HouseNum INT NOT NULL,
  City VARCHAR(25) NOT NULL,
  State VARCHAR(25) NOT NULL,
  Zipcode INT NOT NULL,
  JobType INT NOT NULL DEFAULT 0,
  Salary INT NOT NULL,
  CONSTRAINT EMPPK
  PRIMARY KEY (EmpNumber),
  CONSTRAINT EMP_FK
  FOREIGN KEY (JobType) REFERENCES JOB(TypeCode)
  ON DELETE SET DEFAULT ON UPDATE CASCADE,
  UNIQUE (SSN)
);


CREATE TABLE TREATMENT
(
  Ilness_Type VARCHAR(30) NOT NULL,
  PRIMARY KEY (Ilness_Type)
);

CREATE TABLE SPEC_DOCTOR
(
  SpecID INT NOT NULL,
  Description VARCHAR(20) NOT NULL,
  PRIMARY KEY (SpecID)
);

CREATE TABLE DOCTOR
(
  EmpNumber INT NOT NULL,
  License VARCHAR(20) NOT NULL,
  SpecID INT DEFAULT -1,
  PRIMARY KEY (EmpNumber),
  CONSTRAINT DOCFK
  FOREIGN KEY (EmpNumber) REFERENCES EMPLOYEES(EmpNumber)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT DOCTOR_SPECFK
  FOREIGN KEY (SpecID) REFERENCES SPEC_DOCTOR(SpecID)
  ON DELETE SET DEFAULT ON UPDATE CASCADE,
  UNIQUE (License)
);

CREATE TABLE NURSE
(
  Registration VARCHAR(40) NOT NULL,
  EmpNumber INT NOT NULL,
  PRIMARY KEY (EmpNumber),
  CONSTRAINT NURSPK
  FOREIGN KEY (EmpNumber) REFERENCES EMPLOYEES(EmpNumber)
  ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE (Registration)
);

CREATE TABLE ROOM_TYPE
(
  Code INT NOT NULL,
  Description VARCHAR(20) NOT NULL,
  PRIMARY KEY (Code)
);


CREATE TABLE ROOM
(
  PRoom VARCHAR(6) NOT NULL,
  Nurse INT NOT NULL DEFAULT 222222,
  TypeCode INT DEFAULT 0,
  PRIMARY KEY (PRoom),
  CONSTRAINT PATFROOM
  FOREIGN KEY (Nurse) REFERENCES NURSE(EmpNumber)
  ON DELETE SET DEFAULT ON UPDATE CASCADE,
  CONSTRAINT ROOM_TYPEFK
  FOREIGN KEY (TypeCode) REFERENCES ROOM_TYPE(Code)
  ON DELETE SET DEFAULT ON UPDATE CASCADE
);


CREATE TABLE RECEPCIONIST
(
  TypingSpeed INT NOT NULL,
  EmpNumber INT NOT NULL,
  PRIMARY KEY (EmpNumber),
  CONSTRAINT RECEPTSK
  FOREIGN KEY (EmpNumber) REFERENCES EMPLOYEES(EmpNumber)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MEDICINE
(
  Code VARCHAR(10) NOT NULL,
  MedInfo VARCHAR(60) NOT NULL,
  MedPrice DECIMAL(5,2) NOT NULL,
  MedQuantity INT NOT NULL,
  PRIMARY KEY (Code)
);

CREATE TABLE CONTAINS
(
  Ilness_Type VARCHAR(30) NOT NULL,
  Code VARCHAR(10) NOT NULL,
  PRIMARY KEY (Ilness_Type,Code),
  CONSTRAINT CONTFKMED
  FOREIGN KEY (Ilness_Type) REFERENCES TREATMENT(Ilness_Type)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Code) REFERENCES MEDICINE(Code)
);

CREATE TABLE PATIENT
(
  PatientId INT NOT NULL,
  SSN CHAR(16) NOT NULL,
  Fname VARCHAR(15) NOT NULL,
  LName VARCHAR(20) NOT NULL,
  DOB DATE NOT NULL,
  Gender CHAR(1) NOT NULL,
  Age INT NOT NULL,
  PhoneNum VARCHAR(14) NOT NULL,
  Street VARCHAR(30) NOT NULL,
  HouseNum INT NOT NULL,
  City VARCHAR(25) NOT NULL,
  State VARCHAR(25) NOT NULL,
  Zipcode INT NOT NULL,
  ERVISIT BOOLEAN NOT NULL,
  DateAdmitted DATE NOT NULL,
  AdmtMonth VARCHAR(20) NOT NULL,
  AdmtYear INT NOT NULL,
  DateDischarg DATE,
  Doctor INT NOT NULL DEFAULT 111111,
  PRoom VARCHAR(6) NOT NULL DEFAULT '0000',
  CONSTRAINT PATPK
  PRIMARY KEY (PatientId),
  CONSTRAINT PATFKDOC
  FOREIGN KEY (Doctor) REFERENCES DOCTOR(EmpNumber)
  ON DELETE SET DEFAULT ON UPDATE CASCADE,
  CONSTRAINT PATFROOM
  FOREIGN KEY (PRoom) REFERENCES ROOM(PRoom)
  ON DELETE SET DEFAULT ON UPDATE CASCADE,
  UNIQUE (SSN)
);

CREATE TABLE RECORD
(
  RecordNum INT NOT NULL,
  ApptDate DATE NOT NULL,
  PTObsert VARCHAR(30) NOT NULL,
  PatientId INT NOT NULL,
  ReceptWorked INT NOT NULL DEFAULT 333333,
  PRIMARY KEY (RecordNum, PatientId),
  CONSTRAINT RECFKPAT
  FOREIGN KEY (PatientId) REFERENCES PATIENT(PatientId)
  ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT RECFKRECEP
  FOREIGN KEY (ReceptWorked) REFERENCES RECEPCIONIST(EmpNumber)
  ON DELETE SET DEFAULT ON UPDATE CASCADE
);


CREATE TABLE RECEIVES
(
  PatientId INT NOT NULL,
  Ilness_Type VARCHAR(30) NOT NULL,
  PRIMARY KEY (PatientId,Ilness_Type),
  CONSTRAINT RECEFKPAT
  FOREIGN KEY (PatientId) REFERENCES PATIENT(PatientId)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Ilness_Type) REFERENCES TREATMENT (Ilness_Type)
);
